export const featuredGears = [
  {
    id: 1,
    name: "Mountain Tent Pro",
    category: "Camping",
    image: "/images/gears/tent.jpg",
    price: 25,
    rating: 4.9,
    reviews: 128,
    location: "Dhaka",
    verified: true,
  },
  {
    id: 2,
    name: "Explorer Backpack",
    category: "Hiking",
    image: "/images/gears/backpack.jpg",
    price: 15,
    rating: 4.8,
    reviews: 96,
    location: "Chattogram",
    verified: true,
  },
  {
    id: 3,
    name: "Carbon Mountain Bike",
    category: "Cycling",
    image: "/images/gears/bike.jpg",
    price: 45,
    rating: 5,
    reviews: 76,
    location: "Sylhet",
    verified: true,
  },
  {
    id: 4,
    name: "Climbing Kit",
    category: "Climbing",
    image: "/images/gears/climbing.jpg",
    price: 30,
    rating: 4.9,
    reviews: 51,
    location: "Rangamati",
    verified: true,
  },
];
